# These are supported funding model platforms

github: [LekoArts]
patreon: AJHalili2006
open_collective: # Replace with a single Open Collective username
ko_fi: # leave it blank for a while
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
liberapay: AndreiJirohHaliliDev2006
custom: # Replace with a single custom sponsorship URL
